# Generated by Django 2.1.2 on 2018-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relevancia_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('relevancia', models.FloatField()),
                ('relevancia_inicial', models.FloatField()),
            ],
        ),
    ]
